version: '3'

services:
  node:
    container_name: node_findrunas
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongo_findrunas
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=db_nomina
    ports:
      - "27017:27017"
    logging:
      driver: "none"
